version: '3'
services:
  producer:
    image: 'hystrix-example-producer:1.0'
    ports:
      - '9090:9090'
    networks:
      - 'default'
  consumer:
    image: 'hystrix-example-consumer:1.0'
    ports:
      - '8080:8080'
    environment:
      PRODUCER_ENDPOINT: 'http://producer'
      PRODUCER_PORT: '9090'
    networks:
      - 'default'
networks:
  default: